apiVersion: v1
kind: Service
metadata:
  name: beee-hexa-vue
  labels:
    app: hexa-vue
    component: microservice
spec:
  ports:
  - name: 4321-4321
    port: 4321
    protocol: TCP
    targetPort: 4321
  selector:
    app: hexa-vue
  sessionAffinity: None
  type: ClusterIP